algoritmo "funcoes"

var
 numero1,numero2: inteiro

 //aqui começa a nossa função, é aqui que ela é declarada

 funcao somar(numero1,numero2:inteiro):inteiro
 
   var
inicio

   retorne numero1+numero2
   
  fimfuncao

  inicio
  
    leia(numero1)
    leia(numero2)
    
    //aqui começa a nossa função, é aqui que ela é declarada
    
    escreval(somar(numero1,numero2))
fimalgoritmo
